local Range = require("codedash.lib.range")

describe("Range", function()
  describe("new", function()
    it("creates a range with lo and hi", function()
      local r = Range.new(0, 100)
      assert.equal(0, r.lo)
      assert.equal(100, r.hi)
    end)

    it("provides a linear mapper", function()
      local r = Range.new(0, 100)
      assert.equal(0,   r.mapper(0))
      assert.equal(50,  r.mapper(0.5))
      assert.equal(100, r.mapper(1))
    end)

    it("handles reversed range", function()
      local r = Range.new(240, 0)
      assert.equal(240, r.mapper(0))
      assert.equal(120, r.mapper(0.5))
      assert.equal(0,   r.mapper(1))
    end)

    it("handles negative values", function()
      local r = Range.new(-10, 10)
      assert.equal(-10, r.mapper(0))
      assert.equal(0,   r.mapper(0.5))
      assert.equal(10,  r.mapper(1))
    end)

    it("handles equal lo and hi", function()
      local r = Range.new(5, 5)
      assert.equal(5, r.mapper(0))
      assert.equal(5, r.mapper(0.5))
      assert.equal(5, r.mapper(1))
    end)

    it("errors on non-numeric lo", function()
      assert.has_error(function()
        Range.new("a", 100)
      end)
    end)

    it("errors on non-numeric hi", function()
      assert.has_error(function()
        Range.new(0, "b")
      end)
    end)
  end)

  describe("from_pair", function()
    it("parses a { lo, hi } table", function()
      local r = Range.from_pair({ 0, 100 })
      assert.equal(0, r.lo)
      assert.equal(100, r.hi)
      assert.equal(50, r.mapper(0.5))
    end)

    it("errors on non-table", function()
      assert.has_error(function()
        Range.from_pair("bad")
      end)
    end)

    it("errors on wrong length", function()
      assert.has_error(function()
        Range.from_pair({ 1 })
      end)
      assert.has_error(function()
        Range.from_pair({ 1, 2, 3 })
      end)
    end)

    it("includes context in error message", function()
      local ok, err = pcall(function()
        Range.from_pair("bad", "hue")
      end)
      assert.is_false(ok)
      assert.truthy(err:find("hue"))
    end)
  end)

  describe("is_range", function()
    it("returns true for Range objects", function()
      local r = Range.new(0, 1)
      assert.is_true(Range.is_range(r))
    end)

    it("returns false for plain tables", function()
      assert.is_false(Range.is_range({ lo = 0, hi = 1 }))
    end)

    it("returns false for non-tables", function()
      assert.is_false(Range.is_range(42))
      assert.is_false(Range.is_range(nil))
      assert.is_false(Range.is_range("range"))
    end)
  end)
end)
